#!/bin/bash
#SBATCH -p ipuq    # partition (queue)
#SBATCH -N 1 # number of nodes
#SBATCH -n 32 # number of cores
#            #SBATCH --gres=ipu:4
#            #SBATCH --mem 128G # memory pool for all cores   # Bug in Slurm 20.02.5 torel@simula.no https://github.com/SchedMD/slurm/blob/master/NEWS
#SBATCH -t 1-1:00 # time (D-HH:MM)
#    #SBATCH --exclusive
#SBATCH --mail-type=ALL
#SBATCH --mail-user=luk@simula.no
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR

ulimit -s 10240
mkdir -p ~/output/ipuq

module purge

module load slurm/20.02.7

#module load graphcore/vipu/1.16.0           # vipu-cli for IPUPOD64 m2000
#module load graphcore/sdk/2.4.0             # Poplar 2.4.0
#module load graphcore/tf/2.4.0_tf2.4.4      # Poplar 2.4.0  Tensorflow v2.4.4
module load graphcore/sdk/2.3.0
module load graphcore/vipu/1.15.1
export IPUOF_CONFIG_PATH=/cm/shared/apps/graphcore/vipu/etc/ipuof.conf.d/p64_cl_a01_a16.conf

module load openmpi/gcc/64/4.0.5
# module use osu-micro-benchmarks-mpich-5.6.3
# module use osu-micro-benchmarks-mvapich-5.6.3
module load numactl/gcc/2.0.13

export OMPI_MCA_opal_common_ucx_opal_mem_hooks=1
export OMPI_MCA_pml_ucx_verbose=100
export OMPI_MCA_btl_openib_warn_no_device_params_found=1
export OMPI_MCA_btl_openib_allow_ib=1
export OMPI_MCA_pml="^ucx"
export OMPI_MCA_btl_openib_if_include="mlx5_4:1"
export OMPI_MCA_btl=openib,self
export OMPI_MCA_btl_tcp_if_exclude=lo,dis0,eno1,eno2,enp113s0f0,ib0,ib1,enp33s0f0,enp33s0f1

export IPUOF_CONFIG_PATH=/cm/shared/apps/graphcore/vipu/etc/ipuof.conf.d/p64_cl_a01_a16.conf

# Command


# mpirun -np $SLURM_NTASKS -H ipu-pod64-server1 --mca btl_openib_if_include mlx5_4:1 --mca btl self  --mca pml ucx -- \
srun --mpi=pmi2 -n $SLURM_NTASKS --ntasks 1 -- \
./build/pastis -i /home/lukb/git/PASTIS/tests/scope_77k.fa -c 77040 --af sim_mat.mtx --ckthr 1 --sfa #--absw --bsz 350000
# ./build/pastis -i /global/D1/projects/ipumer/datasets/metaclust/metaclust50_50K.fasta -c 500000 --af sim_mat.mtx --ckthr 1 --sxa 49 --absw


 
# export POPLAR_ENGINE_OPTIONS='{"autoReport.all":"true", "autoReport.directory":"/home/lukb/git/PASTIS/build/profile", "autoReport.executionProfileProgramRunCount":"20"}'
# srun --mpi=pmi2 -n $SLURM_NTASKS --ntasks 1 -E -- \
#   ./build/pastis -i /home/lukb/git/PASTIS/tests/scope_77k.fa -c 77040 --af sim_mat.mtx --ckthr 1 --absw --bsz 350000